apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pplzbaqf7-python
  janus-idp.io/tekton: pplzbaqf7-python
  backstage.io/kubernetes-id: pplzbaqf7-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pplzbaqf7-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
